/*------------------------------------------------------------  
Author:       Gianluca Calcagni
Company:      Waeg
Description:  Used to enable the CPQ triggers in Process Builder

History
2019-10-10    Gianluca Calcagni    Created test class
------------------------------------------------------------*/
@isTest
private class CpqEnableTriggersTest {



    @isTest
    static void testCpqEnableTriggers() {
        CpqEnableTriggers.cpqEnableTriggers();
    }



}