/**********************************
11-Dec-2020: AS: Class commented cause the logic is no longer required.
***********************************/

@isTest
public class SalesAreaTriggerHandler_Test {
    

    @isTest
    public static void salesAreaTest(){
/*        
        Account acc = TestUtility.createCommercialCustomer('Commercial Account');
        insert acc;

        Account acc1 = TestUtility.createCustomerLocation('Cust Loc',acc);
        insert acc1;
        
        Sales_area__c s1 = new sales_area__c();
        s1.Active__c = true;
        s1.Customer_Name__c = acc1.id;
        s1.Customer_Group_4__c = 'B06 Distributor';
        insert s1;
        
        s1.Active__c = false;
        update s1;
        
        s1.Customer_Group_4__c = 'B27 Blender B2B';
        update s1;
        
        delete s1;
     */   
    }

}